branch: master
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: helm package . --app-version=${nextRelease.version} --version=${nextRelease.version} --destination=build/
  - - "@semantic-release/github"
    - assets:
        - path: build/relaynet-pong-*.tgz
