apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: pong-test
  labels:
    app: relaynet-pong
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relaynet-pong
  template:
    metadata:
      labels:
        app: relaynet-pong
        component: queue
    spec:
      containers:
        - name: queue
          image: relaycorp/relaynet-pong:v1.1.2
          command: ['node', 'build/main/bin/background-queue.js']
          env:
            - name: REDIS_HOST
              value: redis
            - name: POHTTP_TLS_REQUIRED
              value: 'false'
            - name: VAULT_URL
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: letmein
            - name: VAULT_KV_PREFIX
              value: 'session-keys'

              # We should be supporting multiple keys so we can do key rotation.
              # See: https://github.com/relaycorp/relaynet-pong/issues/14
            - name: ENDPOINT_PRIVATE_KEY
              value: the-key
