apiVersion: apps/v1
kind: Deployment
metadata:
  name: background_queue
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/background_queue-secret.yml") . | sha256sum }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
        pong.relaycorp.tech/component: queue
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: queue
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "relaycorp/relaynet-pong:v{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: ['node', 'build/main/bin/background-queue.js']
          envFrom:
            - configMapRef:
                name: {{ include "..fullname" . }}
            - secretRef:
                name: {{ include "..fullname" . }}-background_queue
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
